---
- name: pull and deploy jupyter base notebook with self-signed certificate
  hosts: jupyter
  remote_user: jovyan
  become: true
  tasks:
    # install docker.io with apt-get
    - name: install docker
      apt:
        update_cache: yes
        force_apt_get: yes
        name: docker.io
        state: present

    # create target directory for jupyter-notebook
    - name: Create destination folder for jupyter
      ansible.builtin.file:
        path: /home/jovyan/jupyter-folder
        state: directory
        owner: jovyan
        mode: "0755"

    # create target directory for certs
    - name: create destination directory for generated certificates
      ansible.builtin.file:
        path: /certs
        state: directory
        owner: jovyan
        mode: "0755"

    # drop in root ca configuration file
    - name: copy root ca config file to target host
      ansible.builtin.copy:
        src: /etc/ansible/jupyter-docker-ansible-https/ssl-config/ca_cert.cnf
        dest: /certs/ca_cert.cnf
        owner: jovyan
        group: users
        mode: "0755"

    # drop in server cert configuration file
    - name: copy server cert config file to target host
      ansible.builtin.copy:
        src: /etc/ansible/jupyter-docker-ansible-https/ssl-config/server_cert.cnf
        dest: /certs/server_cert.cnf
        owner: jovyan
        group: users
        mode: "0755"

     # drop in server cert extensions configuration file
    - name: copy root ca config file to target host
      ansible.builtin.copy:
        src: /etc/ansible/jupyter-docker-ansible-https/ssl-config/server_ext.cnf
        dest: /certs/server_ext.cnf
        owner: jovyan
        group: users
        mode: "0755"

    # run certificate generation script on target server
    - name: run generate-certs script
      ansible.builtin.script: /etc/ansible/jupyter-docker-ansible-https/ssl-config/gen_root_server_certificates.sh

    # pull jupyter-base docker image
    - name: pull jupyter base image
      docker_container:
        name: jupyter
        image: quay.io/jupyter/base-notebook
        state: started
        restart_policy: always
        published_ports:
          - 443:8888
        volumes:
          - /certs:/certs
          - /home/jovyan/jupyter-folder:/home/jovyan/jupyter-folder
        command: jupyter notebook --notebook-dir ~/jupyter-folder --certfile /certs/server.crt --keyfile /certs/server.key --ip 0.0.0.0 --no-browser

    # enable docker service
    - name: enable docker on host boot
      systemd:
        name: docker
        enabled: true
